### PR TITLE
TR strategy: properly reset the bounds duals and set the warm-start information

### PR DESCRIPTION
**Pull request by cvanaret**
Properly update the WarmstartInformation object: handle phase switches, errors, etc.
Two fixes in TrustRegionStrategy:
- loop over all variables to reset the multipliers when TR constraints are active;
- reset the feasibility multipliers as well;

### CODE REVIEW

**Comment by odow** [comment]
Can we test the TR without BQPD?

**Comment by cvanaret** [comment]
Yes, we can assemble a trust-region SLP method with HiGHS as LP solver.
So far, I've fixed lack of convergence on infeasible problems for SLP methods. I'm still working on properly setting the warmstart information.

**Comment by leyffer** [comment]
Excellent.
It would be good to also test it with BQPD, just to make make sure the two solvers behave the same on smaller instances.
Eventually, we should add an EQP phase and get a second order method.
Sven

Sven Leyffer
Senior Computational Mathematician and Deputy Director
Mathematics and Computer Science Division
Argonne National Laboratory
________________________________

**Comment by odow** [comment]
> It would be good to also test it with BQPD

Sure. But this requires us to be able to compile a version of Uno that includes BQPD on a public CI instance.

**Pull request merged**
