### PR TITLE
Update release.yml

### PR DESCRIPTION
**Pull request by amontoison**
@cvanaret 
I tested the script for the release on my fork and added some fixes.
I have now an example of release automatically generated here:
https://github.com/amontoison/Uno/releases/tag/v1.2.0

### CODE REVIEW

**Review by cvanaret — APPROVED** [review]

**Comment by cvanaret** [comment]
Neat stuff! Thank you!

**Comment by cvanaret** [comment]
@amontoison do you know if there's a way to automatically create a new discussion for the release in Announcements, like https://github.com/cvanaret/Uno/discussions/15?

**Comment by amontoison** [comment]
@cvanaret 
I never implemented a workflow for that but somethink like this should work:
```yaml
name: Post Release Announcement

on:
  release:
    types: [published]  # Se déclenche lorsqu'une release est publiée

jobs:
  delay_and_announce:
    runs-on: ubuntu-latest

    steps:
    - name: Attendre 24 heures
      run: sleep $((24 * 60 * 60))  # Attend 24 heures (86400 secondes)

    - name: Obtenir les notes de release
      id: get_release_notes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Récupère les informations de la dernière release
        response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/releases/latest)
        
        # Extraire le titre et le corps de la release
        echo "::set-output name=title::$(echo "$response" | jq -r '.name')"
        echo "::set-output name=body::$(echo "$response" | jq -r '.body')"

    - name: Poster l'annonce dans les Discussions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Remplacez '123456' par l'ID de la catégorie où l'annonce doit être postée
        curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/discussions \
          -d "{\"title\": \"Nouvelle Release : ${{ steps.get_release_notes.outputs.title }}\", \"body\": \"${{ steps.get_release_notes.outputs.body }}\", \"category_id\": 123456}"
```
The idea is to wait a few hours or one day after that a release is created to do a new announcement.

It will copy-paste the content of the release note and use it for the announcement.
I added a "sleep" because the workflow that cross-compiles binaries and create the release doesn't contain the changelog / release note.
So it will give you one day to add it before that the announcement is created.

**Comment by cvanaret** [comment]
@amontoison thank you very much!

**Comment by amontoison** [comment]
Do you want that I open a PR to add a workflow?
I can do that next week and try it on my fork.

**Comment by cvanaret** [comment]
If you find time, sure. It's not urgent though.
Thanks!

**Pull request merged**
