### PR TITLE
Use CMake's fortran name mangling

### PR DESCRIPTION
**Pull request by worc4021**
This PR introduces applies  CMake's FortranCInterface name mangling to allow other toolchains to compile uno. No change in functionality is expected.

### CODE REVIEW

**Comment by cvanaret** [comment]
@amontoison It doesn't look like the PR is colliding with our efforts into Uno_jll, can you confirm?

**Comment by amontoison** [comment]
It seems to be fine.
I should add a CI build here that generates a local Uno_jll.
I can quickly do that tomorrow.

**Comment by cvanaret** [comment]
> It seems to be fine. I should add a CI build here that generates a local Uno_jll. I can quickly do that tomorrow.

Thanks!
It's probably related to https://github.com/cvanaret/Uno/pull/49?

**Comment by amontoison** [comment]
After that #53 is merged, it will safe to merge any PR if CI builds passed.

**Review by cvanaret — DISMISSED** [review]

**Comment by cvanaret** [comment]
@amontoison for some reason, the current PR doesn't trigger `julia-tests-ubuntu.yml` (probably because it was submitted before yours). Do we need to add a type in:
```
pull_request:
    types: [opened, synchronize, reopened]
```
?

**Comment by worc4021** [comment]
Hello,

The usual behaviour is that the triggers are governed by the "main" branch. I.e. if the main branch has a policy to trigger a build when a PR is opened then all PRs being opened will trigger a build. If a branch that is itself in a PR will be adding some new policy, then these new policies are not triggered up until they are policies of the master branch itself. The counter part is usually more important. So if you got annoyed by builds triggering every time you modify something and you want to mute them, then this doesn't actually remove the protection of the master branch up until this has been approved and merged.

In the case on hand the uno master branch will be protected from accidentally braking the Julia interface from now on.

**Comment by amontoison** [comment]
> @amontoison for some reason, the current PR doesn't trigger `julia-tests-ubuntu.yml` (probably because it was submitted before yours). Do we need to add a type in:
> 
> ```
> pull_request:
>     types: [opened, synchronize, reopened]
> ```
> 
> ?

It's because @worc4021 needs to rebase this branch to include the last commits added in `main`.
You can do that with the following commands:
```shell
git remote add upstream https://github.com/cvanaret/Uno.git
git fetch upstream
git rebase upstream/main
git push -f
```

**Review by cvanaret — APPROVED** [review]

**Comment by cvanaret** [comment]
It's a wrap! Thanks a lot @worc4021!

**Pull request merged**
